baseURL = "/"
languageCode = "en-us"
title = "FFMT - FFXIV Modding Tool"
theme = "kube"
description = "FFMT is a crossplatform and Open Source commandline interface for Final Fantasy XIV Modding with a goal to reach feature parity with TexTools."
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  github = "fosspill" # add your github profile name
  email = "myemail@myaddress.xxx"

[[menu.main]]
    name = "Documentation"
    weight = -100
    url = "/docs/"
